version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER:  gameuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB:      gamedb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_URL: "postgres://gameuser:password@db:5432/gamedb?sslmode=disable"

      APP_SERVER_PORT:       "8080"
      APP_SERVER_READ_TIMEOUT:  "15s"
      APP_SERVER_WRITE_TIMEOUT: "15s"

      APP_AUTH_JWT_SECRET:  "super-secret-key"
      APP_AUTH_ACCESS_TTL:  "15m"
      APP_AUTH_REFRESH_TTL: "168h"

      APP_AUTH_SMTP_HOST: "smtp.example.com"
      APP_AUTH_SMTP_PORT: "587"
      APP_AUTH_SMTP_USER: "you@example.com"
      APP_AUTH_SMTP_PASS: "your-smtp-password"
      APP_AUTH_SMTP_FROM: "noreply@example.com"
volumes:
  db-data: